[package]
name = "pika-chat-frontend"
version = "0.1.0"
edition = "2021"

[dependencies]
yew = { version = "0.20", features = ["csr"] }
serde = { version = "1.0", features = ["derive"] }
gloo-net = "0.3"
wasm-bindgen = "0.2"
