app = "rust-chatroom-server"

[build]
  dockerfile = "Dockerfile"

[env]
  DATABASE_URL = "sqlite:/app/chat_app.db"
  SECRET_KEY = "secret_key_for_jwt"

[[services]]
  internal_port = 80
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
